<?php

/**
 * Table of contents
 *
 * Add <body> classes
 * Clean up the_excerpt()
 * Hide Wordpress Admin bar
 * Hide Yoast SEO Columns from post/page list view
 * Clean up paragraph tags around images in the_content
 * Remove empty paragraphs from the_content
 * Allow SVG through WordPress Media Uploader
 * Perfect JPGs
 * Limit the number of results shown on search results
 * Remove unnecessary columns
 * Unregister default Wordpres widgets
 * Add an external link to Admin menu
 * Limit the character length in excerpt
 * Remove width and height values from embedded images
 * Add class to links generated by next_posts_link and previous_posts_link
 * Add defer attribute to scripts
 * Disable automatic loading of Contact Form 7 assets
 * Order Custom Post Types by date
 * Hide email from Spam Bots using a shortcode
 *
 */

namespace Roots\Sage\Extras;
use Roots\Sage\Config;


/**
 * Add <body> classes
 */
function body_class($classes) {
  // Add page slug if it doesn't exist
  if (is_single() || is_page() && !is_front_page()) {
    if (!in_array(basename(get_permalink()), $classes)) {
      $classes[] = basename(get_permalink());
    }
  }

  // Add class if sidebar is active
  if (Config\display_sidebar()) {
    $classes[] = 'sidebar-primary';
  }

  return $classes;
}
add_filter('body_class', __NAMESPACE__ . '\\body_class');


/**
 * Clean up the_excerpt()
 */
function excerpt_more() {
  return ' &hellip; <a href="' . get_permalink() . '">' . __('Continued', 'sage') . '</a>';
}
add_filter('excerpt_more', __NAMESPACE__ . '\\excerpt_more');


/**
 * Hide Wordpress Admin bar
 */
add_filter('show_admin_bar', __NAMESPACE__ . '\\__return_false');


/**
 * Hide Yoast SEO Columns from post/page list view
 */
add_filter( 'wpseo_use_page_analysis', __NAMESPACE__ . '\\__return_false' );


/**
 * Clean up paragraph tags around images in content
 */
function filter_ptags_on_images($content){
   return preg_replace('/<p>\s*(<a .*>)?\s*(<img .* \/>)\s*(<\/a>)?\s*<\/p>/iU', '\1\2\3', $content);
}
add_filter('the_content', __NAMESPACE__ . '\\filter_ptags_on_images');


/**
 * Remove empty paragraphs from the_content
 */
function remove_empty_p( $content ){
  // clean up p tags around block elements
  $content = preg_replace( array(
    '#<p>\s*<(div|aside|section|article|header|footer)#',
    '#</(div|aside|section|article|header|footer)>\s*</p>#',
    '#</(div|aside|section|article|header|footer)>\s*<br ?/?>#',
    '#<(div|aside|section|article|header|footer)(.*?)>\s*</p>#',
    '#<p>\s*</(div|aside|section|article|header|footer)#',
  ), array(
    '<$1',
    '</$1>',
    '</$1>',
    '<$1$2>',
    '</$1',
  ), $content );

  return preg_replace('#<p>(\s|&nbsp;)*+(<br\s*/*>)*(\s|&nbsp;)*</p>#i', '', $content);
}
add_filter( 'the_content', __NAMESPACE__ . '\\remove_empty_p', 20, 1 );


/**
 * Allow SVG through WordPress Media Uploader
 * Source: https://css-tricks.com/snippets/wordpress/allow-svg-through-wordpress-media-uploader/
 */
function cc_mime_types($mimes) {
  $mimes['svg'] = 'image/svg+xml';
  return $mimes;
}
add_filter('upload_mimes', __NAMESPACE__ . '\\cc_mime_types');


/**
 * Perfect JPGs
 */
function reen_jpeg_quality() {
  return 100;
}
add_filter( 'jpeg_quality', __NAMESPACE__ . '\\reen_jpeg_quality' );


/**
 * Limit the number of results shown on search results
 */
function postsperpage($limits) {
  if (is_search()) {
    global $wp_query;
    $wp_query->query_vars['posts_per_page'] = 12;
  }
  return $limits;
}
add_filter('post_limits', __NAMESPACE__ . '\\postsperpage');


/**
 * Remove unnecessary columns
 * For custom post types, use manage_${post_type}_posts_columns
 * Source: http://codex.wordpress.org/Plugin_API/Filter_Reference/manage_edit-post_type_columns
 */
function remove_posts_columns($columns) {
  //unset($columns['author']);
  //unset($columns['categories']);
  //unset($columns['comments']);
  //unset($columns['date']);
  unset($columns['tags']);
  return $columns;
}
add_filter( 'manage_edit-post_columns', __NAMESPACE__ . '\\remove_posts_columns', 10, 1 );


/**
 * Unregister default Wordpres widgets
 */
function unregister_default_widgets() {
  unregister_widget('WP_Widget_Pages');
  unregister_widget('WP_Widget_Calendar');
  unregister_widget('WP_Widget_Archives');
  unregister_widget('WP_Widget_Links');
  unregister_widget('WP_Widget_Meta');
  unregister_widget('WP_Widget_Search');
  unregister_widget('WP_Widget_Text');
  unregister_widget('WP_Widget_Categories');
  unregister_widget('WP_Widget_Recent_Posts');
  unregister_widget('WP_Widget_Recent_Comments');
  unregister_widget('WP_Widget_RSS');
  unregister_widget('WP_Widget_Tag_Cloud');

  // Unregister Widget link from Navigation
  // unregister_widget('WP_Nav_Menu_Widget');
}
add_action('widgets_init', __NAMESPACE__ . '\\unregister_default_widgets', 11);


/**
 * Add an external link to Admin menu
 */
function add_toolbar_items($admin_bar){
  $admin_bar->add_menu( array(
    'id'    => 'reen-support-link',
    'title' => 'Support',
    'href'  => '#',
    'meta'  => array(
      'title' => __('Support'),
      'target' => '_blank',
      'class' => 'reen-support-link'
    ),
  ));
}
add_action('admin_bar_menu', __NAMESPACE__ . '\\add_toolbar_items', 100);


/**
 * Limit the character length in excerpt
 * Source: http://wordpress.stackexchange.com/questions/70913/how-can-i-limit-the-character-length-in-excerpt
 */
function get_excerpt($limit, $source = null){
  if($source == "content" ? ($excerpt = get_the_content()) : ($excerpt = get_the_excerpt()));
  $excerpt = preg_replace(" (\[.*?\])",'',$excerpt);
  $excerpt = strip_shortcodes($excerpt);
  $excerpt = strip_tags($excerpt);
  $excerpt = substr($excerpt, 0, $limit);
  $excerpt = substr($excerpt, 0, strripos($excerpt, " "));
  $excerpt = trim(preg_replace( '/\s+/', ' ', $excerpt));
  $excerpt = $excerpt.' ...';
  return $excerpt;
}


/**
 * Remove width and height values from embedded images
 * Source: https://css-tricks.com/snippets/wordpress/remove-width-and-height-attributes-from-inserted-images/
 */
function remove_width_attribute( $html ) {
  $html = preg_replace( '/(width|height)="\d*"\s/', "", $html );
  return $html;
}
add_filter( 'post_thumbnail_html', __NAMESPACE__ . '\\remove_width_attribute', 10 );
add_filter( 'image_send_to_editor', __NAMESPACE__ . '\\remove_width_attribute', 10 );


/**
 * Add class to links generated by next_posts_link and previous_posts_link
 * https://css-tricks.com/snippets/wordpress/add-class-to-links-generated-by-next_posts_link-and-previous_posts_link/
 */
function posts_link_attributes() {
  return 'class="post-nav-link"';
}
add_filter('next_posts_link_attributes', __NAMESPACE__ . '\\posts_link_attributes');
add_filter('previous_posts_link_attributes', __NAMESPACE__ . '\\posts_link_attributes');


/**
 * Add defer attribute to scripts
 * Source: https://gist.github.com/toscho/1584783
 */
if(!is_user_logged_in()) {
  add_filter( 'clean_url', function( $url ) {
    if ( FALSE === strpos( $url, '.js' ) ) {
      // not our file
      return $url;
    }
      // Must be a ', not "!
      return "$url' defer='defer";
  }, 11, 1 );
}


/**
 * Disable automatic loading of Contact Form 7 assets
 * Source: http://contactform7.com/loading-javascript-and-stylesheet-only-when-it-is-necessary/
 *
 * To load the files on pages which contain contact forms, use the following conditions.
 * Note that wpcf7_enqueue_scripts() and wpcf7_enqueue_styles() must be called before wp_head() is called.
 *
 * if ( function_exists( 'wpcf7_enqueue_scripts' ) ) {
 *   wpcf7_enqueue_scripts();
 * }
 *
 * if ( function_exists( 'wpcf7_enqueue_styles' ) ) {
 *   wpcf7_enqueue_styles();
 * }
 *
 */
add_filter( 'wpcf7_load_js', __NAMESPACE__ . '\\__return_false' );
add_filter( 'wpcf7_load_css', __NAMESPACE__ . '\\__return_false' );


/**
 * Order Custom Post Types by date
 */
// function wpse_post_types_admin_order( $wp_query ) {
//   if ( is_admin() && !isset( $_GET['orderby'] ) ) {
//     // Get the post type from the query
//     $post_type = $wp_query->query['post_type'];
//     if ( in_array( $post_type, array('custom-post-type') ) ) {
//       $wp_query->set('orderby', 'date');
//       $wp_query->set('order', 'DESC');
//     }
//   }
// }
// add_filter('pre_get_posts', 'wpse_post_types_admin_order');


/**
 * Removing Jetpack CSS
 * Source: https://css-tricks.com/snippets/wordpress/removing-jetpack-css/
 */
// First, make sure Jetpack doesn't concatenate all its CSS
add_filter( 'jetpack_implode_frontend_css', '__return_false' );
// Then, remove each CSS file, one at a time
function jeherve_remove_all_jp_css() {
  wp_deregister_style( 'AtD_style' ); // After the Deadline
  wp_deregister_style( 'jetpack_likes' ); // Likes
  wp_deregister_style( 'jetpack_related-posts' ); //Related Posts
  wp_deregister_style( 'jetpack-carousel' ); // Carousel
  wp_deregister_style( 'grunion.css' ); // Grunion contact form
  wp_deregister_style( 'the-neverending-homepage' ); // Infinite Scroll
  wp_deregister_style( 'infinity-twentyten' ); // Infinite Scroll - Twentyten Theme
  wp_deregister_style( 'infinity-twentyeleven' ); // Infinite Scroll - Twentyeleven Theme
  wp_deregister_style( 'infinity-twentytwelve' ); // Infinite Scroll - Twentytwelve Theme
  wp_deregister_style( 'noticons' ); // Notes
  wp_deregister_style( 'post-by-email' ); // Post by Email
  wp_deregister_style( 'publicize' ); // Publicize
  wp_deregister_style( 'sharedaddy' ); // Sharedaddy
  wp_deregister_style( 'sharing' ); // Sharedaddy Sharing
  wp_deregister_style( 'stats_reports_css' ); // Stats
  wp_deregister_style( 'jetpack-widgets' ); // Widgets
  wp_deregister_style( 'jetpack-slideshow' ); // Slideshows
  wp_deregister_style( 'presentations' ); // Presentation shortcode
  wp_deregister_style( 'jetpack-subscriptions' ); // Subscriptions
  wp_deregister_style( 'tiled-gallery' ); // Tiled Galleries
  wp_deregister_style( 'widget-conditions' ); // Widget Visibility
  wp_deregister_style( 'jetpack_display_posts_widget' ); // Display Posts Widget
  wp_deregister_style( 'gravatar-profile-widget' ); // Gravatar Widget
  wp_deregister_style( 'widget-grid-and-list' ); // Top Posts widget
  wp_deregister_style( 'jetpack-widgets' ); // Widgets
}
add_action('wp_print_styles', 'jeherve_remove_all_jp_css' );


/**
 * Hide email from Spam Bots using a shortcode
 * http://codex.wordpress.org/Function_Reference/antispambot
 *
 * Default usage
 * In content:  [email]john.doe@mysite.com[/email]
 * In theme:    echo antispambot( 'john.doe@mysite.com' );
 *
 * @param array  $atts    Shortcode attributes. Not used.
 * @param string $content The shortcode content. Should be an email address.
 *
 * @return string The obfuscated email address.
 */
function wpcodex_hide_email_shortcode( $atts , $content = null ) {
  if ( ! is_email( $content ) ) {
    return;
  }

  return antispambot( $content );
}
add_shortcode( 'email', __NAMESPACE__ . '\\wpcodex_hide_email_shortcode' );
add_filter( 'widget_text', __NAMESPACE__ . '\\shortcode_unautop' );
add_filter( 'widget_text', __NAMESPACE__ . '\\do_shortcode' );
