<?php

/**
 * Table of contents
 *
 * Add <body> classes
 * Clean up the_excerpt()
 * Hide Wordpress Admin bar
 * Hide Yoast SEO Columns from post/page list view
 * Clean up paragraph tags around images in the_content
 * Remove empty paragraphs from the_content
 * Allow SVG through WordPress Media Uploader
 * Perfect JPGs
 * Limit the number of results shown on search results
 * Remove unnecessary columns
 * Unregister default Wordpres widgets
 * Add an external link to Admin menu
 * Limit the character length in excerpt
 * Remove width and height values from embedded images
 * Add class to links generated by next_posts_link and previous_posts_link
 * Add defer attribute to scripts
 * Disable automatic loading of Contact Form 7 assets
 * Order Custom Post Types by date
 * Hide email from Spam Bots using a shortcode
 *
 */

namespace Roots\Sage\Extras;
use Roots\Sage\Config;


/**
 * Add <body> classes
 */
function body_class($classes) {
  // Add page slug if it doesn't exist
  if (is_single() || is_page() && !is_front_page()) {
    if (!in_array(basename(get_permalink()), $classes)) {
      $classes[] = basename(get_permalink());
    }
  }

  // Add class if sidebar is active
  if (Config\display_sidebar()) {
    $classes[] = 'sidebar-primary';
  }

  return $classes;
}
add_filter('body_class', __NAMESPACE__ . '\\body_class');


/**
 * Clean up the_excerpt()
 */
function excerpt_more() {
  return ' &hellip; <a href="' . get_permalink() . '">' . __('Continued', 'sage') . '</a>';
}
add_filter('excerpt_more', __NAMESPACE__ . '\\excerpt_more');


/**
 * Hide Wordpress Admin bar
 */
add_filter('show_admin_bar', '__return_false');


/**
 * Hide Yoast SEO Columns from post/page list view
 */
add_filter( 'wpseo_use_page_analysis', '__return_false' );


/**
 * Clean up paragraph tags around images in content
 */
function filter_ptags_on_images($content){
   return preg_replace('/<p>\s*(<a .*>)?\s*(<img .* \/>)\s*(<\/a>)?\s*<\/p>/iU', '\1\2\3', $content);
}
add_filter('the_content', 'filter_ptags_on_images');


/**
 * Remove empty paragraphs from the_content
 */
add_filter( 'the_content', 'remove_empty_p', 20, 1 );
function remove_empty_p( $content ){
  // clean up p tags around block elements
  $content = preg_replace( array(
    '#<p>\s*<(div|aside|section|article|header|footer)#',
    '#</(div|aside|section|article|header|footer)>\s*</p>#',
    '#</(div|aside|section|article|header|footer)>\s*<br ?/?>#',
    '#<(div|aside|section|article|header|footer)(.*?)>\s*</p>#',
    '#<p>\s*</(div|aside|section|article|header|footer)#',
  ), array(
    '<$1',
    '</$1>',
    '</$1>',
    '<$1$2>',
    '</$1',
  ), $content );

  return preg_replace('#<p>(\s|&nbsp;)*+(<br\s*/*>)*(\s|&nbsp;)*</p>#i', '', $content);
}


/**
 * Allow SVG through WordPress Media Uploader
 * Source: https://css-tricks.com/snippets/wordpress/allow-svg-through-wordpress-media-uploader/
 */
function cc_mime_types($mimes) {
  $mimes['svg'] = 'image/svg+xml';
  return $mimes;
}
add_filter('upload_mimes', 'cc_mime_types');


/**
 * Perfect JPGs
 */
add_filter( 'jpeg_quality', 'reen_jpeg_quality' );
function reen_jpeg_quality() {
  return 100;
}


/**
 * Limit the number of results shown on search results
 */
function postsperpage($limits) {
  if (is_search()) {
    global $wp_query;
    $wp_query->query_vars['posts_per_page'] = 12;
  }
  return $limits;
}
add_filter('post_limits', 'postsperpage');


/**
 * Remove unnecessary columns
 */
function remove_posts_columns($columns) {
   // Remove 'Author' Column
  // unset($columns['author']);
  // Remove 'Categories' Column
  // unset($columns['categories']);
  // Remove 'Tags' Column
  unset($columns['tags']);
  // Remove 'Comments' Column
  unset($columns['comments']);

  return $columns;
}


/**
 * Unregister default Wordpres widgets
 */
function unregister_default_widgets() {
  unregister_widget('WP_Widget_Pages');
  unregister_widget('WP_Widget_Calendar');
  unregister_widget('WP_Widget_Archives');
  unregister_widget('WP_Widget_Links');
  unregister_widget('WP_Widget_Meta');
  unregister_widget('WP_Widget_Search');
  unregister_widget('WP_Widget_Text');
  unregister_widget('WP_Widget_Categories');
  unregister_widget('WP_Widget_Recent_Posts');
  unregister_widget('WP_Widget_Recent_Comments');
  unregister_widget('WP_Widget_RSS');
  unregister_widget('WP_Widget_Tag_Cloud');

  // Unregister Widget link from Navigation
  // unregister_widget('WP_Nav_Menu_Widget');
}
add_action('widgets_init', 'unregister_default_widgets', 11);


/**
 * Add an external link to Admin menu
 */
add_action('admin_bar_menu', 'add_toolbar_items', 100);
function add_toolbar_items($admin_bar){
 $admin_bar->add_menu( array(
   'id'    => 'reen-support-link',
   'title' => 'Support',
   'href'  => '#',
   'meta'  => array(
     'title' => __('Support'),
     'target' => '_blank',
     'class' => 'reen-support-link'
   ),
 ));
}

/**
 * Limit the character length in excerpt
 * Source: http://wordpress.stackexchange.com/questions/70913/how-can-i-limit-the-character-length-in-excerpt
 */
function get_excerpt($limit, $source = null){
  if($source == "content" ? ($excerpt = get_the_content()) : ($excerpt = get_the_excerpt()));
  $excerpt = preg_replace(" (\[.*?\])",'',$excerpt);
  $excerpt = strip_shortcodes($excerpt);
  $excerpt = strip_tags($excerpt);
  $excerpt = substr($excerpt, 0, $limit);
  $excerpt = substr($excerpt, 0, strripos($excerpt, " "));
  $excerpt = trim(preg_replace( '/\s+/', ' ', $excerpt));
  $excerpt = $excerpt.' ...';
  return $excerpt;
}


/**
 * Remove width and height values from embedded images
 * Source: https://css-tricks.com/snippets/wordpress/remove-width-and-height-attributes-from-inserted-images/
 */
add_filter( 'post_thumbnail_html', 'remove_width_attribute', 10 );
add_filter( 'image_send_to_editor', 'remove_width_attribute', 10 );
function remove_width_attribute( $html ) {
   $html = preg_replace( '/(width|height)="\d*"\s/', "", $html );
   return $html;
}


/**
 * Add class to links generated by next_posts_link and previous_posts_link
 * https://css-tricks.com/snippets/wordpress/add-class-to-links-generated-by-next_posts_link-and-previous_posts_link/
 */
add_filter('next_posts_link_attributes', 'posts_link_attributes');
add_filter('previous_posts_link_attributes', 'posts_link_attributes');
function posts_link_attributes() {
    return 'class="post-nav-link"';
}


/**
 * Add defer attribute to scripts
 * Source: https://gist.github.com/toscho/1584783
 */
if(!is_user_logged_in()) {
  add_filter( 'clean_url', function( $url ) {
    if ( FALSE === strpos( $url, '.js' ) ) {
      // not our file
      return $url;
    }
      // Must be a ', not "!
      return "$url' defer='defer";
  }, 11, 1 );
}


/**
 * Disable automatic loading of Contact Form 7 assets
 * Source: http://contactform7.com/loading-javascript-and-stylesheet-only-when-it-is-necessary/
 *
 * To load the files on pages which contain contact forms, use the following conditions.
 * Note that wpcf7_enqueue_scripts() and wpcf7_enqueue_styles() must be called before wp_head() is called.
 *
 * if ( function_exists( 'wpcf7_enqueue_scripts' ) ) {
 *   wpcf7_enqueue_scripts();
 * }
 *
 * if ( function_exists( 'wpcf7_enqueue_styles' ) ) {
 *   wpcf7_enqueue_styles();
 * }
 *
 */
add_filter( 'wpcf7_load_js', '__return_false' );
add_filter( 'wpcf7_load_css', '__return_false' );


/**
 * Order Custom Post Types by date
 */
// function wpse_post_types_admin_order( $wp_query ) {
//   if ( is_admin() && !isset( $_GET['orderby'] ) ) {
//     // Get the post type from the query
//     $post_type = $wp_query->query['post_type'];
//     if ( in_array( $post_type, array('custom-post-type') ) ) {
//       $wp_query->set('orderby', 'date');
//       $wp_query->set('order', 'DESC');
//     }
//   }
// }
// add_filter('pre_get_posts', 'wpse_post_types_admin_order');


/**
 * Hide email from Spam Bots using a shortcode
 * http://codex.wordpress.org/Function_Reference/antispambot
 *
 * Default usage
 * In content:  [email]john.doe@mysite.com[/email]
 * In theme:    echo antispambot( 'john.doe@mysite.com' );
 *
 * @param array  $atts    Shortcode attributes. Not used.
 * @param string $content The shortcode content. Should be an email address.
 *
 * @return string The obfuscated email address.
 */
function wpcodex_hide_email_shortcode( $atts , $content = null ) {
  if ( ! is_email( $content ) ) {
    return;
  }

  return antispambot( $content );
}
add_shortcode( 'email', 'wpcodex_hide_email_shortcode' );
add_filter( 'widget_text', 'shortcode_unautop' );
add_filter( 'widget_text', 'do_shortcode' );
